Repository Kusitms-29th-Meetup-TeamE/Frontend, pull requests merged in 2024-05, with the labels that each got.

#9 feature/#7: header
  package.json
  public/assets/ddoba_logo.png
  src/app/layout.tsx
  src/components/common-components/common/Header.tsx
  src/hooks/useToast.tsx
  tailwind.config.ts
  yarn.lock
Labels: 😈 chaemin, 📍 Feat, 💄 Style

#13 feature/#11/footer
  public/assets/ddoba_logo_black-footer.svg
  src/app/layout.tsx
  src/app/seohyun/page.tsx
  src/components/common-components/common/Footer.tsx
Labels: 🐧 seohyun, 📍 Feat, 💄 Style

#10 feature/#8: main top
  public/assets/main/how1.png
  public/assets/main/how2.png
  public/assets/main/how3.png
  public/assets/main/main_banner.png
  public/assets/pin_icon.svg
  src/app/chaemin/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common-components/animation/ScrollAnimation.tsx
  src/components/common-components/animation/ScrollContainer.tsx
  src/components/common-components/common/Footer.tsx
  src/components/common-components/common/Header.tsx
  src/components/common-components/tag/Tag.tsx
  src/components/common-components/tag/Tag.types.ts
  src/components/common-components/tag/index.ts
  src/components/main/MainTitle.tsx
  src/components/main/RecommendItem.tsx
  src/components/main/ShareProfile.tsx
  src/containers/main/HowTo.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
  src/types/user.tsx
  tailwind.config.ts
Labels: 😈 chaemin, 📍 Feat, 💄 Style

#19 feature/#17: button component
  src/app/chaemin/page.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/common-components/button/index.ts
Labels: 😈 chaemin, 📍 Feat, 💄 Style, ✅ Test

#20 feature/#18: input component
  src/app/chaemin/page.tsx
  src/components/common-components/input/Input.tsx
  src/components/common-components/input/Input.types.ts
  src/components/common-components/input/index.ts
Labels: 😈 chaemin, 📍 Feat, 💄 Style, ✅ Test

#27 feature/#21: login publishing
  public/assets/components/check_box_gray06.svg
  public/assets/components/check_box_gray08.svg
  public/assets/components/check_box_orange06.svg
  public/assets/components/ddoba_logo_black-footer.svg
  public/assets/components/kakao.svg
  public/assets/ddoba_logo_text.svg
  src/app/login/page.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/check-box/CheckBox.tsx
  src/components/common-components/check-box/Checkbox.tsx
  src/components/common-components/common/Footer.tsx
  src/components/signUp/SignUpTitle.tsx
  src/containers/main/Point.tsx
Labels: 🐧 seohyun, 📍 Feat, 💄 Style

#33 style/#29: modal custom
  src/components/common-components/button/Button.tsx
  src/components/common-components/global-modal/ErrorModal.tsx
  src/components/common-components/global-modal/SuccessModal.tsx
  src/components/common-components/modal/Modal.tsx
  src/components/common-components/modal/ModalDescription.tsx
  src/components/common-components/modal/ModalFooter.tsx
  src/components/common-components/modal/ModalTitle.tsx
  tailwind.config.ts
Labels: 😈 chaemin, 💄 Style

#35 feature/#23: main api
  src/api/index.ts
  src/api/main.ts
  src/components/common-components/skeleton/Skeleton.tsx
  src/components/main/RecommendItem.tsx
  src/components/main/ShareProfile.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
  src/hooks/useMain.tsx
Labels: 😈 chaemin, 📍 Feat

#28 feature/#26: sign up
  package.json
  public/assets/signup/form1.png
  public/assets/signup/form2.png
  public/assets/signup/form3.png
  public/assets/signup/form4.png
  public/assets/signup/form5.png
  src/app/chaemin/page.tsx
  src/app/signup/page.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/common-components/common/Header.tsx
  src/components/common-components/global-modal/ErrorModal.tsx
  src/components/common-components/global-modal/SuccessModal.tsx
  src/components/common-components/input/Input.types.ts
  src/components/common-components/modal/Modal.tsx
  src/components/common-components/modal/ModalClose.tsx
  src/components/common-components/select-box/SelectBox.types.ts
  src/components/signUp/SearchAddressModal.tsx
  src/constants/object.ts
  src/containers/signup/FifthForm.tsx
  src/containers/signup/FirstForm.tsx
  src/containers/signup/FourthForm.tsx
  src/containers/signup/SecondForm.tsx
  src/containers/signup/ThirdForm.tsx
  yarn.lock
Labels: 😈 chaemin, 📍 Feat, 💄 Style

#41 fix/#40: deploy error
  src/app/chaemin/page.tsx
  src/components/common-components/modal/ModalSubTitle.tsx
  src/components/common-components/select-box/SelectBox.tsx
  src/components/common-components/select-box/SelectBox.types.ts
  src/containers/signup/FifthForm.tsx
Labels: 😈 chaemin, 🔨 Fix, deploy

#47 deploy: 1차 배포 - 최종
  src/app/chaemin/page.tsx
  src/components/common-components/modal/ModalSubTitle.tsx
  src/components/common-components/select-box/SelectBox.tsx
  src/components/common-components/select-box/SelectBox.types.ts
  src/containers/signup/FifthForm.tsx
Labels: deploy

#49 feature/#43: kakao signup UI
  public/assets/signup/kakao/step1.png
  public/assets/signup/kakao/step2.png
  src/app/signup/kakao/page.tsx
  src/components/common-components/modal/Modal.tsx
  src/components/common-components/modal/ModalClose.tsx
  src/components/common-components/modal/ModalDescription.tsx
  src/components/common-components/modal/ModalFooter.tsx
  src/components/common-components/modal/ModalSubTitle.tsx
  src/components/common-components/modal/ModalTitle.tsx
  src/components/signUp/SearchAddressModal.tsx
  src/containers/signup/FifthForm.tsx
  src/containers/signup/FirstForm.tsx
Labels: 😈 chaemin, 🌈 Update, 💄 Style

#46 feature/#44: chat UI
  src/app/chaemin/page.tsx
  src/app/chat/activity/page.tsx
  src/app/chat/page.tsx
  src/app/chat/share/page.tsx
  src/app/globals.css
  src/components/chat/AppointmentModal.tsx
  src/components/chat/MyMsgItem.tsx
  src/components/chat/OneRoomItem.tsx
  src/components/chat/OtherMsgItem.tsx
  src/components/chat/RoomItem.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/input/Input.tsx
  src/components/common-components/modal/Modal.tsx
  src/constants/object.ts
  src/containers/chat/ChatRoom.tsx
  src/containers/chat/EmptyChat.tsx
  src/containers/chat/RoomList.tsx
  tailwind.config.ts
Labels: 😈 chaemin, 🌈 Update, 📍 Feat, 💄 Style

#54 feature/#51: chat api
  package.json
  src/api/chat.ts
  src/app/chaemin/page.tsx
  src/app/chat/activity/page.tsx
  src/app/chat/page.tsx
  src/app/chat/share/page.tsx
  src/app/login/oauth2/callback/kakao/page.tsx
  src/app/onboarding/page.tsx
  src/app/seohyun/page.tsx
  src/app/signup/kakao/page.tsx
  src/components/chat/AppointmentModal.tsx
  src/components/chat/AppointmentMsgItem.tsx
  src/components/chat/MyAppointmentMsgItem.tsx
  src/components/chat/MyMsgItem.tsx
  src/components/chat/OneRoomItem.tsx
  src/components/chat/OtherMsgItem.tsx
  src/components/chat/RoomItem.tsx
  src/components/onboarding/OnboardingFrame.tsx
  src/components/onboarding/fourth-items/FourthChip.tsx
  src/constants/.gitkeep
  src/containers/chat/ChatRoom.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
  src/containers/signup/FifthForm.tsx
  src/containers/signup/FourthForm.tsx
  src/containers/signup/SecondForm.tsx
  src/containers/signup/ThirdForm.tsx
  src/hooks/api/useChat.ts
  src/hooks/api/useMain.ts
  src/hooks/api/useUser.ts
  src/hooks/useToast.ts
  src/store/chatStore.ts
  src/types/chat.ts
  src/types/user.ts
  src/utils/index.ts
  vercel.json
  yarn.lock
Labels: 😈 chaemin, 📍 Feat

#63 deploy: 배포 1.5
  src/components/signup/SearchAddressModal.tsx
Labels: deploy

#64 fix: build error 1.5
  src/components/common-components/check-box/CheckBox.tsx
Labels: 🐧 seohyun, 🔨 Fix, deploy

#65 deploy: 배포 1.7
  src/components/common-components/check-box/CheckBox.tsx
Labels: deploy

#67 fix: vercel.json setting
  vercel.json
Labels: 🐧 seohyun, 🔨 Fix, deploy

#68 deploy: 배포 1.8
  vercel.json
Labels: 🐧 seohyun, deploy

#48 feature/#45: join activity publishing
  public/assets/components/activity-top-banner.png
  src/app/globals.css
  src/app/join/detail/[id]/page.tsx
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/onboarding/page.tsx
  src/components/common-components/chip/Chip.tsx
  src/components/common-components/chip/Chip.types.ts
  src/components/common-components/common/Header.tsx
  src/components/common-components/input/Input.tsx
  src/components/common-components/pagination/Pagination.tsx
  src/components/common-components/pagination/Pagination.types.ts
  src/components/common-components/pagination/index.ts
  src/components/common-components/textarea/Textarea.tsx
  src/components/common-components/textarea/Textarea.types.ts
  src/components/common-components/textarea/index.ts
  src/components/join/ActivityBanner.tsx
  src/components/join/JoinActivityModal.tsx
  src/components/join/JoinSlider.tsx
  src/components/main/RecommendItem.tsx
  src/components/onboarding/OnboardingFrame.tsx
  src/components/onboarding/fourth-items/FourthChip.tsx
  src/components/onboarding/fourth-items/FourthChipCloud.tsx
  src/constants/object.ts
  src/containers/join/ActivityContainer.tsx
  src/containers/join/ChipContainer.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/onboarding/ZeroStep.tsx
  src/store/join/selectedJoinChipStore.ts
  src/store/onboarding/onboardingStepStore.ts
  src/types/modal.ts
  tailwind.config.ts
Labels: 🐧 seohyun, 📍 Feat, 💄 Style

#73 feature/#72: mypage sidebar
  src/app/chaemin/test/page.tsx
  src/app/layout.tsx
  src/components/mypage/Sidebar.tsx
Labels: 😈 chaemin, 📍 Feat, 💄 Style

#70 refactor/#39: scroll container
  src/app/page.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
Labels: 😈 chaemin, 🤖 Refactor

#71 feature/#53: local login api
  src/api/user.ts
  src/app/login/page.tsx
  src/app/signup/kakao/page.tsx
  src/components/common-components/common/Header.tsx
  src/hooks/api/useUser.ts
Labels: 🐧 seohyun, 📍 Feat, ✅ Test

#76 feature/#66: chat list
  next.config.mjs
  public/assets/chat/emoticon.png
  src/api/index.ts
  src/app/chaemin/page.tsx
  src/app/chat/activity/page.tsx
  src/app/chat/share/page.tsx
  src/app/globals.css
  src/components/chat/AppointmentModal.tsx
  src/components/chat/OneRoomItem.tsx
  src/components/chat/RoomItem.tsx
  src/components/common-components/common/Header.tsx
  src/containers/chat/ChatRoom.tsx
  src/containers/chat/RoomList.tsx
  src/store/join/selectedJoinChipStore.ts
  src/utils/index.ts
Labels: 😈 chaemin, 📍 Feat

#74 deploy: v0.2.0
  next.config.mjs
  public/assets/chat/emoticon.png
  public/assets/components/activity-top-banner.png
  src/api/index.ts
  src/api/user.ts
  src/app/chaemin/page.tsx
  src/app/chaemin/test/page.tsx
  src/app/chat/activity/page.tsx
  src/app/chat/share/page.tsx
  src/app/globals.css
  src/app/join/detail/[id]/page.tsx
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/onboarding/page.tsx
  src/app/page.tsx
  src/app/signup/kakao/page.tsx
  src/components/chat/AppointmentModal.tsx
  src/components/chat/OneRoomItem.tsx
  src/components/chat/RoomItem.tsx
  src/components/common-components/chip/Chip.tsx
  src/components/common-components/chip/Chip.types.ts
  src/components/common-components/common/Header.tsx
  src/components/common-components/input/Input.tsx
  src/components/common-components/pagination/Pagination.tsx
  src/components/common-components/pagination/Pagination.types.ts
  src/components/common-components/pagination/index.ts
  src/components/common-components/textarea/Textarea.tsx
  src/components/common-components/textarea/Textarea.types.ts
  src/components/common-components/textarea/index.ts
  src/components/join/ActivityBanner.tsx
  src/components/join/JoinActivityModal.tsx
  src/components/join/JoinSlider.tsx
  src/components/main/RecommendItem.tsx
  src/components/mypage/Sidebar.tsx
  src/components/onboarding/OnboardingFrame.tsx
  src/components/onboarding/fourth-items/FourthChip.tsx
  src/components/onboarding/fourth-items/FourthChipCloud.tsx
  src/constants/object.ts
  src/containers/chat/ChatRoom.tsx
  src/containers/chat/RoomList.tsx
  src/containers/join/ActivityContainer.tsx
  src/containers/join/ChipContainer.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
  src/containers/onboarding/ZeroStep.tsx
  src/hooks/api/useUser.ts
  src/store/join/selectedJoinChipStore.ts
  src/store/onboarding/onboardingStepStore.ts
  src/types/modal.ts
  src/utils/index.ts
  tailwind.config.ts
Labels: deploy

#80 fix/#69: input
  src/api/user.ts
  src/components/common-components/input/Input.tsx
  src/containers/signup/ThirdForm.tsx
Labels: 😈 chaemin, 💄 Style, 🔨 Fix

#81 deploy: v.0.2.1
  src/api/user.ts
  src/components/common-components/input/Input.tsx
  src/containers/signup/ThirdForm.tsx
Labels: deploy

#82 hotfix: 로그인 시 헤더 버그
  src/components/common-components/common/Header.tsx
Labels: 🐧 seohyun, 🔨 Fix

#84 deploy: v.0.2.2
  src/components/common-components/common/Header.tsx
Labels: deploy

#50 feature/#42: signup-api
  src/api/user.ts
  src/app/signup/page.tsx
  src/components/common-components/global-modal/ErrorModal.tsx
  src/components/common-components/select-box/SelectBox.tsx
  src/constants/object.ts
  src/containers/signup/FifthForm.tsx
  src/containers/signup/FourthForm.tsx
  src/containers/signup/ThirdForm.tsx
  src/hooks/api/useUser.ts
  src/types/user.ts
Labels: 😈 chaemin, 📍 Feat

#78 feature/#77: mypage learning profile + api 연동 + 라우팅... 등등
  next.config.mjs
  src/api/mypage.ts
  src/app/chaemin/page.tsx
  src/app/mypage/learn/page.tsx
  src/app/mypage/learn/profile/page.tsx
  src/app/mypage/learn/recieved/page.tsx
  src/app/mypage/learn/reviews/page.tsx
  src/app/mypage/page.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/common-components/select-box/SelectBox.tsx
  src/components/mypage/MyExperienceItem.tsx
  src/components/mypage/MyLearnListItem.tsx
  src/components/mypage/MypageTItle.tsx
  src/components/mypage/ReviewItem.tsx
  src/components/mypage/Sidebar.tsx
  src/components/signup/SearchAddressModal.tsx
  src/constants/object.ts
  src/containers/mypage/LearnProfile.tsx
  src/hooks/api/useMyPage.ts
  src/hooks/useToast.ts
  src/types/mypage.ts
Labels: 😈 chaemin, 📍 Feat, 💄 Style

#86 feature/#59: learning sharing publishing
  public/assets/share/profile.png
  public/assets/share/slider-item.png
  public/assets/share/slider-next.png
  src/app/join/detail/[id]/page.tsx
  src/app/join/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/app/share/page.tsx
  src/components/common-components/check-box/Checkbox.tsx
  src/components/common-components/chip/Chip.tsx
  src/components/common-components/chip/Chip.types.ts
  src/components/common-components/common/Header.tsx
  src/components/common-components/select-box/SelectBox.tsx
  src/components/common-components/select-box/SelectBox.types.ts
  src/components/share/LearningItem.tsx
  src/components/share/LearningProfile.tsx
  src/components/share/OtherLearningItem.tsx
  src/components/share/ReviewItem.tsx
  src/components/share/ReviewSlider.tsx
  src/constants/object.ts
  src/containers/join/ActivityContainer.tsx
  src/containers/main/Point.tsx
  src/containers/main/ShareExperience.tsx
  src/containers/onboarding/FifthStep.tsx
  src/containers/onboarding/SecondStep.tsx
  src/containers/onboarding/ThirdStep.tsx
  src/containers/onboarding/ZeroStep.tsx
  src/store/share/selectedLearningChipStore.ts
  src/types/activity.ts
Labels: 🐧 seohyun, 📍 Feat, 💄 Style

#90 feature/#89/mypage UI api
  package.json
  src/api/mypage.ts
  src/app/layout.tsx
  src/app/mypage/activity/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/learn/page.tsx
  src/app/mypage/learn/profile/page.tsx
  src/app/mypage/learn/recieved/page.tsx
  src/app/mypage/learn/reviews/[reviewId]/page.tsx
  src/app/mypage/learn/reviews/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/point/page.tsx
  src/components/common-components/check-box/Checkbox.tsx
  src/components/common-components/common/Header.tsx
  src/components/common-components/input/Input.types.ts
  src/components/main/RecommendItem.tsx
  src/components/mypage/Sidebar.tsx
  src/constants/object.ts
  src/containers/mypage/LearnProfile.tsx
  src/hooks/api/useMyPage.ts
  src/styles/font.ts
  src/utils/index.ts
  yarn.lock
Labels: 😈 chaemin, 📍 Feat, 💄 Style

#99 hotfix
  src/app/mypage/point/page.tsx
Labels: 😈 chaemin, 🔨 Fix

#94 feature/#52: join activity api
  src/api/join.ts
  src/app/join/detail/[id]/page.tsx
  src/app/join/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/app/share/page.tsx
  src/components/common-components/chip/Chip.tsx
  src/components/common-components/chip/Chip.types.ts
  src/components/join/JoinSlider.tsx
  src/components/main/RecommendItem.tsx
  src/containers/join/ActivityContainer.tsx
  src/containers/join/ChipContainer.tsx
  src/containers/main/RecommendActivity.tsx
  src/hooks/api/useActivity.ts
  src/store/join/selectedJoinChipStore.ts
  src/types/activity.ts
Labels: 🐧 seohyun, 📍 Feat, ✅ Test

#97 refactor/#96: chat-plus
  public/assets/ddoba_emoticon.png
  src/app/chat/activity/page.tsx
  src/app/chat/share/page.tsx
  src/components/chat/AppointmentMsgItem.tsx
  src/components/chat/OneRoomItem.tsx
  src/components/chat/OtherMsgItem.tsx
  src/components/chat/RoomItem.tsx
  src/components/common-components/common/Header.tsx
  src/containers/chat/ChatRoom.tsx
  src/containers/chat/EmptyChat.tsx
Labels: 😈 chaemin, 🤖 Refactor

#100 feature/#98: mypage calendar
  package.json
  src/api/mypage.ts
  src/app/chaemin/cal/page.tsx
  src/app/mypage/calendar/page.tsx
  src/app/mypage/point/page.tsx
  src/components/common-components/common/Header.tsx
  src/components/mypage/MyCalendar.tsx
  src/components/mypage/Sidebar.tsx
  src/hooks/api/useMyPage.ts
  src/styles/calendar.css
  src/types/mypage.ts
  yarn.lock
Labels: 😈 chaemin, 📍 Feat, 💄 Style, ✅ Test

#104 hotfix for deploy
  src/hooks/api/useActivity.ts
Labels: deploy

#102 deploy: v0.4.0
  package.json
  public/assets/ddoba_emoticon.png
  src/api/join.ts
  src/api/mypage.ts
  src/app/chaemin/cal/page.tsx
  src/app/chat/activity/page.tsx
  src/app/chat/share/page.tsx
  src/app/join/detail/[id]/page.tsx
  src/app/join/page.tsx
  src/app/mypage/calendar/page.tsx
  src/app/mypage/point/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/app/share/page.tsx
  src/components/chat/AppointmentMsgItem.tsx
  src/components/chat/OneRoomItem.tsx
  src/components/chat/OtherMsgItem.tsx
  src/components/chat/RoomItem.tsx
  src/components/common-components/chip/Chip.tsx
  src/components/common-components/chip/Chip.types.ts
  src/components/common-components/common/Header.tsx
  src/components/join/JoinSlider.tsx
  src/components/main/RecommendItem.tsx
  src/components/mypage/MyCalendar.tsx
  src/components/mypage/Sidebar.tsx
  src/containers/chat/ChatRoom.tsx
  src/containers/chat/EmptyChat.tsx
  src/containers/join/ActivityContainer.tsx
  src/containers/join/ChipContainer.tsx
  src/containers/main/RecommendActivity.tsx
  src/hooks/api/useActivity.ts
  src/hooks/api/useMyPage.ts
  src/store/join/selectedJoinChipStore.ts
  src/styles/calendar.css
  src/types/activity.ts
  src/types/mypage.ts
  yarn.lock
Labels: deploy

#105 fix/#93: signup logic
  public/assets/signup/ddoba_org.png
  public/assets/signup/ddoba_person.png
  src/api/user.ts
  src/app/signup/page.tsx
  src/containers/signup/FirstForm.tsx
  src/containers/signup/ThirdForm.tsx
  src/hooks/api/useUser.ts
Labels: 😈 chaemin, 🔨 Fix

#101 feature/#75: learning sharing api
  src/api/share.ts
  src/app/join/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/app/share/page.tsx
  src/components/common-components/chip/Chip.tsx
  src/components/common-components/chip/Chip.types.ts
  src/components/main/RecommendItem.tsx
  src/components/main/ShareProfile.tsx
  src/components/share/LearningItem.tsx
  src/components/share/LearningProfile.tsx
  src/components/share/OtherLearningItem.tsx
  src/components/share/ReviewItem.tsx
  src/components/share/ReviewSlider.tsx
  src/constants/object.ts
  src/containers/join/ChipContainer.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
  src/hooks/api/useLearning.ts
  src/types/activity.ts
  src/types/learning.ts
  src/types/user.ts
Labels: 🐧 seohyun, 📍 Feat, ✅ Test

#111 feature/#79: loading component
  package.json
  src/app/chat/activity/page.tsx
  src/app/chat/share/page.tsx
  src/app/seohyun/page.tsx
  src/components/common-components/spinner/Spinner.tsx
  src/components/common-components/spinner/index.ts
  yarn.lock
Labels: 🐧 seohyun, 💄 Style, ✅ Test

#106 update/#95: common-issue
  src/api/main.ts
  src/app/chaemin/page.tsx
  src/app/chat/activity/page.tsx
  src/app/chat/share/page.tsx
  src/app/join/detail/[id]/page.tsx
  src/app/join/page.tsx
  src/app/login/oauth2/callback/kakao/page.tsx
  src/app/mypage/activity/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/learn/reviews/[reviewId]/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/app/signup/page.tsx
  src/components/chat/AppointmentMsgItem.tsx
  src/components/chat/MyAppointmentMsgItem.tsx
  src/components/common-components/common/Footer.tsx
  src/components/common-components/common/Header.tsx
  src/components/mypage/Sidebar.tsx
  src/components/onboarding/first-items/FirstSlider.tsx
  src/components/share/ReviewSlider.tsx
  src/components/signup/SearchAddressModal.tsx
  src/constants/object.ts
  src/containers/chat/ChatRoom.tsx
  src/containers/main/HowTo.tsx
  src/containers/main/Notice.tsx
  src/containers/main/RecommendActivity.tsx
  src/containers/main/ShareExperience.tsx
  src/containers/mypage/LearnProfile.tsx
  src/containers/signup/FifthForm.tsx
  src/containers/signup/FourthForm.tsx
  src/containers/signup/ThirdForm.tsx
  src/hooks/api/useUser.ts
Labels: 😈 chaemin, 🔨 Fix

#107 update/#92: ux writing resource
  public/assets/chat/ddoba_directchat.png
  public/assets/chat/ddoba_groupchat.png
  public/next.svg
  public/vercel.svg
  src/app/chat/page.tsx
  src/app/favicon.ico
  src/app/icon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/share/page.tsx
  src/components/chat/AppointmentMsgItem.tsx
  src/components/chat/MyAppointmentMsgItem.tsx
  src/components/common-components/common/Layout.tsx
  src/containers/mypage/LearnProfile.tsx
Labels: 😈 chaemin, 🌈 Update, 🔨 Fix

#113 fix/#112: login bug
  src/api/user.ts
  src/app/login/oauth2/callback/kakao/page.tsx
  src/app/login/page.tsx
  src/components/common-components/check-box/Checkbox.tsx
  src/components/common-components/common/Layout.tsx
Labels: 🐧 seohyun, 🔨 Fix

#115 hotfix
  src/api/main.ts
  src/app/join/page.tsx
  src/app/mypage/activity/page.tsx
  src/app/share/page.tsx
  src/hooks/api/useLearning.ts
Labels: 🔨 Fix

#119 Fix/qa 1
  src/app/login/oauth2/callback/kakao/page.tsx
  src/app/mypage/learn/recieved/page.tsx
  src/components/common-components/common/Footer.tsx
  src/components/common-components/common/Layout.tsx
  src/components/mypage/MyCalendar.tsx
  src/containers/chat/ChatRoom.tsx
  src/containers/signup/SecondForm.tsx
  src/styles/calendar.css
Labels: 😈 chaemin, 🔨 Fix

#118 fix/#116: data exception
  src/app/join/detail/[id]/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/components/mypage/MyLearnListItem.tsx
Labels: 🐧 seohyun, 🔨 Fix

#120 deploy: v0.4.1
  src/app/join/detail/[id]/page.tsx
  src/app/login/oauth2/callback/kakao/page.tsx
  src/app/mypage/learn/recieved/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/components/common-components/common/Footer.tsx
  src/components/common-components/common/Layout.tsx
  src/components/mypage/MyCalendar.tsx
  src/components/mypage/MyLearnListItem.tsx
  src/containers/chat/ChatRoom.tsx
  src/containers/signup/SecondForm.tsx
  src/styles/calendar.css
Labels: deploy

#121 ✅ Test(#117)
  src/app/join/detail/[id]/page.tsx
  src/app/login/oauth2/callback/kakao/page.tsx
  src/app/mypage/edit/page.tsx
  src/components/mypage/MyLearnListItem.tsx
Labels: 😈 chaemin, 🔨 Fix

#125 feature/#103: chat-post
  src/api/chat.ts
  src/app/join/detail/[id]/page.tsx
  src/app/share/detail/[id]/page.tsx
  src/hooks/api/useChat.ts
Labels: 😈 chaemin, 📍 Feat

#162 feature/#161: learn profile save
  src/api/user.ts
  src/components/mypage/MyExperienceItem.tsx
  src/components/share/LearningItem.tsx
  src/constants/object.ts
  src/containers/mypage/LearnProfile.tsx
Labels: 😈 chaemin, 📍 Feat
